// <auto-generated />
namespace AssessmentModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CriterionCriteriaScore_Addded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CriterionCriteriaScore_Addded));
        
        string IMigrationMetadata.Id
        {
            get { return "201603141309579_Criterion-CriteriaScore_Addded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
